<a href="https://colab.research.google.com/github/vghu/densepro/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%91%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%B9_%D0%B1%D0%BB%D0%BE%D0%BA_%7C_%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_%D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D1%81%D0%B5%D1%82%D0%B8_%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D1%8B%D0%B9_%D1%81%D0%BB%D0%BE%D0%B9_(Dense)_%7C_%D0%94%D0%97_Pro_%7C_%D0%A3%D0%98%D0%98%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задание

Самостоятельно напишите нейронную сеть, которая может стать составной частью системы бота для игры в "Крестики-нолики". Используя подготовленную базу изображений, создайте и обучите нейронную сеть, распознающую две категории изображений: крестики и нолики. Добейтесь точности распознавания более 95% (accuracy)


In [ ]:
# Подключение класса для создания нейронной сети прямого распространения
from tensorflow.keras.models import Sequential 
# Подключение класса для создания полносвязного слоя
from tensorflow.keras.layers import Dense 
# Подключение оптимизатора
from tensorflow.keras.optimizers import Adam 
# Подключение утилит для to_categorical
from tensorflow.keras import utils 
# Подключение библиотеки для загрузки изображений
from tensorflow.keras.preprocessing import image 
# Подключение библиотеки для работы с массивами
import numpy as np
# Подключение модуля для работы с файлами
import os
# Подключение библиотек для отрисовки изображений
import matplotlib.pyplot as plt 
from PIL import Image 
# Вывод изображения в ноутбуке, а не в консоли или файле
%matplotlib inline 

In [ ]:
# Загрузка датасета из облака
import gdown
gdown.download('https://storage.yandexcloud.net/aiueducation/Content/base/l3/hw_pro.zip', None, quiet=True)

'hw_pro.zip'

In [ ]:
# Распаковываем архив hw_light.zip в папку hw_light
!unzip -q hw_pro.zip

In [ ]:
# Путь к директории с базой
base_dir = '/content/hw_pro'
# Создание пустого списка для загрузки изображений обучающей выборки
x_train = []
# Создание списка для меток классов
y_train = []
# Задание высоты и ширины загружаемых изображений
img_height = 20
img_width = 20
# Перебор папок в директории базы
for patch in os.listdir(base_dir):
    # Перебор файлов в папках
    for img in os.listdir(base_dir + '/' + patch):
        # Добавление в список изображений текущей картинки
        x_train.append(image.img_to_array(image.load_img(base_dir + '/' + patch + '/' + img,
                                                         target_size=(img_height, img_width),
                                                         color_mode='grayscale')))
        # Добавление в массив меток, соответствующих классам
        if patch == '0':
            y_train.append(0)
        else:
            y_train.append(1)
# Преобразование в numpy-массив загруженных изображений и меток классов
x_train = np.array(x_train)
y_train = np.array(y_train)
# Вывод размерностей
print('Размер массива x_train', x_train.shape)
print('Размер массива y_train', y_train.shape)

Размер массива x_train (102, 20, 20, 1)
Размер массива y_train (102,)


In [ ]:
# Нужно привести обьекты исследования в линейный вид (вектору)
x_train = x_train.reshape(102, 400)
print(x_train.shape)
print(x_train)

(102, 400)
[[255. 255. 255. ... 255. 255. 255.]
 [255. 253. 255. ... 255. 255. 255.]
 [255. 255. 253. ... 255. 255. 255.]
 ...
 [255. 251. 255. ... 255. 255. 255.]
 [255. 253. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [ ]:
# нужно произвести нормирование данных чтобы все элементы были в диапазоне 0-1 типа float
x_train = x_train.astype('float32') #создали обьект формы x_train и типа для каждого элемента float
x_train = x_train / 255 # преобразование каждого числа в обьекте к виду 0-1 типа float


In [ ]:
# чтобы ответ тоже имел вид вектора применяем one_hot_encoding вида to_categorical(y_train, 2)         
y_train = utils.to_categorical(y_train, 2)


In [ ]:
# проверяем сборку данных
print(x_train)

[[1.         1.         1.         ... 1.         1.         1.        ]
 [1.         0.99215686 1.         ... 1.         1.         1.        ]
 [1.         1.         0.99215686 ... 1.         1.         1.        ]
 ...
 [1.         0.9843137  1.         ... 1.         1.         1.        ]
 [1.         0.99215686 1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 1.         1.         1.        ]]


In [ ]:
# проверяем сборку ответов
print(y_train)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [ ]:
# сборка сети
model = Sequential() 
model.add(Dense(800, input_dim=400, activation='relu')) 
model.add(Dense(2, activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.0001), metrics=["accuracy"]) 
model.fit(x_train, y_train, batch_size=25, epochs=10, verbose=1, shuffle=True)
print() # отступ
# вывод характеристик модели
print(model.summary())

Epoch 1/10
5/5 [==============================] - 1s 6ms/step - loss: 0.7563 - accuracy: 0.5392
Epoch 2/10
5/5 [==============================] - 0s 5ms/step - loss: 0.6712 - accuracy: 0.6078
Epoch 3/10
5/5 [==============================] - 0s 5ms/step - loss: 0.6172 - accuracy: 0.5882
Epoch 4/10
5/5 [==============================] - 0s 5ms/step - loss: 0.5341 - accuracy: 0.8333
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 0.4913 - accuracy: 0.8627
Epoch 6/10
5/5 [==============================] - 0s 5ms/step - loss: 0.4486 - accuracy: 0.9314
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.4177 - accuracy: 0.9804
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 0.3893 - accuracy: 0.9706
Epoch 9/10
5/5 [==============================] - 0s 7ms/step - loss: 0.3635 - accuracy: 0.9804
Epoch 10/10
5/5 [==============================] - 0s 5ms/step - loss: 0.3597 - accuracy: 0.9510

Model: "sequential_16"
_______________

настройки 2-ух строк дают стабильно 98-99
model.add(Dense(800, input_dim=400, activation='relu')) 
и 
model.fit(x_train, y_train, batch_size=25, epochs=10, verbose=1, shuffle=True)
т.е. первый слой на 800 нейронов и полаем 400 значений и выборка для обучения по 25 штук, если делать 30 то он запоминает все (вероятно переобучение)
